### ISSUE TITLE
demultiplex

### ISSUE THREAD

**Issue by zhoujt1994** [lhqing/cemba_data#3]
I would suggest running the config file check in the demultiplex step at the beginning. The demultiplex shouldn't be allowed to start if an old version of the config file is provided.

**Comment by lhqing** [comment]
Good suggestion, I added validation before demultiplexing now.

https://github.com/lhqing/cemba_data/commit/ed5dc05e6cdd431446cce0981d95b13ff230cb1f

**Comment by lhqing** [comment]
See https://github.com/lhqing/cemba_data/commit/ed5dc05e6cdd431446cce0981d95b13ff230cb1f
