### ISSUE TITLE
mc template

### ISSUE THREAD

**Issue by jksr** [lhqing/cemba_data#5]
`expand("allc-{mcg_context}/{cell_id}.{mcg_context}-Merge.allc.tsv.gz", cell_id=CELL_IDS),`
-->
`expand("allc-{mcg_context}/{cell_id}.{mcg_context}-Merge.allc.tsv.gz", cell_id=CELL_IDS, mcg_context=mcg_context),`

**Comment by jksr** [comment]
mc template, line 32

**Comment by lhqing** [comment]
Fixed in https://github.com/lhqing/cemba_data/commit/93dab7e21789284805db042b758d370364d6e390
