### ISSUE TITLE
Bismark / Bowtie not writing output to directory

### ISSUE THREAD

**Issue by manoj-hariharan** [lhqing/cemba_data#6]
Running YAP (after re-installation), in Stampede2, I still notice that the BAM files are not getting created in the output directory during the Bismark rule. 

I get zero size files in the bam directory for "MRSA_7-MRSA_8-E4-AD010-R1.trimmed_bismark_bt2.bam" and "MRSA_7-MRSA_8-E4-AD010-R1.trimmed_bismark_bt2_SE_report.txt"

This is how I run the command interactively (using the command from an actual error file) - 

(mapping) login2.stampede2(1275)$ bismark /scratch/02332/hmanoj/utils/hg38  --bowtie2 fastq/MRSA_7-MRSA_8-E4-AD010-R1.trimmed.fq.gz --pbat -o bam/ --temp_dir bam/

I can see no errors. But I get zero size BAM files.

Working directory:
/scratch/02332/hmanoj/PoolAX_Test/snakemake/sbatch/Pool_AX_Test_3cells_sbatch

Please see complete run information attached.

[CompleteRunInfo_StampedeYAP.txt](https://github.com/lhqing/cemba_data/files/5551481/CompleteRunInfo_StampedeYAP.txt)

**Comment by lhqing** [comment]
This is not related to YAP as we discussed, closing this issue
